@echo off
echo Cleaning Prisma cache...
if exist "node_modules\.prisma" rmdir /s /q "node_modules\.prisma"
echo Installing dependencies...
npm install
echo Generating Prisma client...
npx prisma generate
echo Running migrations...
npx prisma migrate deploy
echo Done!
pause 